# =========================================================================
# Demo 18：综合报告页面
# =========================================================================

from latticesvg import GridContainer, TextNode, SVGNode, templates
from utils import heading, save, ColorBox

def demo_18_full_report():
    heading("Demo 18: 综合报告页面")

    page = GridContainer(style={
        "width": "800px",
        "padding": "30px",
        "background-color": "#ffffff",
        "grid-template-columns": ["1fr"],
        "gap": "16px",
    })

    # ── Header ──
    header = GridContainer(style={
        **templates.HEADER,
        "grid-template-columns": ["1fr"],
    })
    header.add(TextNode("LatticeSVG 综合功能报告", style={
        "font-size": "22px",
        "font-weight": "bold",
        "color": "#ffffff",
        "text-align": "center",
    }))
    page.add(header)

    # ── 简介 ──
    page.add(TextNode(
        "本报告由 LatticeSVG 布局引擎自动生成，展示了 CSS Grid 布局、"
        "文本排版、嵌入 SVG 图形等功能的综合效果。",
        style=templates.PARAGRAPH,
    ))

    # ── 两列区域 ──
    two_col = GridContainer(style={
        "grid-template-columns": ["1fr", "1fr"],
        "gap": "20px",
    })

    # 左列：文字
    left = GridContainer(style={
        "grid-template-columns": ["1fr"],
        "gap": "8px",
    })
    left.add(TextNode("核心特性", style=templates.H2))
    left.add(TextNode(
        "• CSS Grid Level 1 布局算法\n"
        "• FreeType 字形精确测量\n"
        "• drawsvg 矢量渲染\n"
        "• 嵌套网格支持\n"
        "• 17 种内置样式模板",
        style={**templates.PARAGRAPH, "white-space": "pre"},
    ))

    two_col.add(left, row=1, col=1)

    # 右列：嵌入 SVG 图形
    chart_svg = '''<svg viewBox="0 0 200 150" xmlns="http://www.w3.org/2000/svg">
  <rect x="10" y="100" width="30" height="40" fill="#e74c3c" rx="3"/>
  <rect x="50" y="60"  width="30" height="80" fill="#3498db" rx="3"/>
  <rect x="90" y="30"  width="30" height="110" fill="#2ecc71" rx="3"/>
  <rect x="130" y="10" width="30" height="130" fill="#f39c12" rx="3"/>
  <line x1="5" y1="145" x2="195" y2="145" stroke="#bdc3c7" stroke-width="1"/>
</svg>'''
    right = GridContainer(style={
        "grid-template-columns": ["1fr"],
        "gap": "5px",
        "background-color": "#f8f9fa",
        "padding": "10px",
    })
    right.add(SVGNode(chart_svg, style={"padding": "5px"}))
    right.add(TextNode("图表：功能覆盖率", style=templates.CAPTION))
    two_col.add(right, row=1, col=2)

    page.add(two_col)

    # ── 色卡 ──
    page.add(TextNode("主题色板", style=templates.H3))
    palette = GridContainer(style={
        "grid-template-columns": ["1fr", "1fr", "1fr", "1fr", "1fr", "1fr"],
        "gap": "8px",
    })
    palette_colors = ["#e74c3c", "#3498db", "#2ecc71", "#f39c12", "#9b59b6", "#1abc9c"]
    for c in palette_colors:
        palette.add(ColorBox(30, 40, **{"background-color": c}))
    page.add(palette)

    # ── Footer ──
    footer = GridContainer(style={
        **templates.FOOTER,
        "grid-template-columns": ["1fr"],
    })
    footer.add(TextNode("Generated by LatticeSVG v0.1.0", style={
        "font-size": "11px",
        "color": "#bdc3c7",
        "text-align": "center",
    }))
    page.add(footer)

    save(page, "18_full_report.svg")
    
if __name__ == "__main__":
    demo_18_full_report()